name: Scheduled Backup and Cleanup (Windows)

on:
  schedule:
    # Runs every day at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  backup_and_cleanup:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Perform Backup
      - name: Run Backup
        run: |
          echo Running backup...
          Compress-Archive -Path ./data/* -DestinationPath backup.zip
          echo Backup completed: backup.zip

      # Step 3: Perform Cleanup
      - name: Run Cleanup
        run: |
          echo Cleaning up old files...
          Get-ChildItem -Path ./data/* -File | Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-30) } | Remove-Item
          echo Cleanup completed
        shell: pwsh
